@startuml affichageGUISynthetique

class MainWindow {
    - pile : QStackedWidget*
    - ecranTitre : EcranTitre*
    - ecranSelectionSauvegarde : EcranSelectionSauvegarde*
    - ecranSelectionModeDeJeu : EcranSelectionModeDeJeu*
    - ecranSelectionNombreJoueurs : EcranSelectionNombreJoueurs*
    - ecranDifficulteArchitechte : EcranDifficulteArchitechte*
    - ecranSaisieNoms : EcranSaisieNoms*
    - ecranChoixRegles : EcranChoixRegles*
    - ecranVitessePartie : EcranVitessePartie*
    - ecranJeu : EcranJeu*
    - victoire : EcranVictoire*

    + MainWindow()
    + showEcran(ecran : QWidget*)

    + getEcranTitre() : EcranTitre*
    + getEcranSelectionSauvegarde() : EcranSelectionSauvegarde*
    + getEcranSelectionModeDeJeu() : EcranSelectionModeDeJeu*
    + getEcranSelectionNombreJoueurs() : EcranSelectionNombreJoueurs*
    + getEcranDifficulteArchitechte() : EcranDifficulteArchitechte*
    + getEcranSaisieNoms() : EcranSaisieNoms*
    + getEcranChoixRegles() : EcranChoixRegles*
    + getEcranVitessePartie() : EcranVitessePartie*
    + getEcranJeu() : EcranJeu*
    + getEcranVictoire() : EcranVictoire*
}

class HexagoneGUIObject extends QObject, QGraphicsItem {
    - hex : QGraphicsPolygonItem
    - outline : QGraphicsPathItem
    - text : QGraphicsTextItem
    - hauteur : QGraphicsTextItem

    + HexagoneGUIObjet(couleur : CouleursAkropolis, description : const string&, height : int, doOutline : const bool[5])
    + boundingRect() const : QRectF
    + void paint(painter : QPainter*, option : const QStyleOptionGraphicsItem*, widget : QWidget*)
}

class CameraMap extends QGraphicsView {
    # wheelEvent(event : QWheelEvent*)
    # mouseMoveEvent(event : QMouseEvent*)
    # mousePressEvent(event : QMouseEvent*)
    + CameraMap(scene : QGraphicsScene*)
    + mouseMoved(mousePos : QPointF) {signal}
    + mousePressed(mousePos : QPointF) {signal}
}

class ChantierQGraphicsView extends QGraphicsView {
    # mousePressEvent(event : QMouseEvent*)
    + ChantierQGraphicsView(scene : QGraphicsScene*, p : QWidget*)
    + onClicked() {signal}
}

abstract AbstractEcran extends QWidget {
    # mainLayout : QVBoxLayout*

    # ecranBasics(titre : const QString&, avecBoutonRetour : bool);
    # template <typename T, typename ClassFille> setupBoutons(data : T&, fille : ClassFille*);
    + AbstractEcran(QWidget* parent = nullptr);
    + backRequested(bool) {signal}
}

class EcranType extends AbstractEcran {
    + EcranType()
    + selectionFinished(arg : Type) {signal}
}

class EcranJeu extends QWidget {
    # nombreJoueurs : size_t 
    # labelNom : QLabel* 
    # labelScore : QLabel* 
    # labelTour : QLabel* 
    # labelPierre : QLabel* 

    # labelRegles : QLabel* 

    # zoneChantier : QWidget* 
    # sceneChantier : QGraphicsScene** 
    # labelsChantier : QLabel** 

    # plateau : QWidget* 
    # vueMap : CameraMap* 
    # sceneMap : QGraphicsScene* 
    # infoJoueurs : QWidget* 

    # labelNomJoueurs : QLabel** 
    # labelScoreJoueurs : QLabel** 
    # labelPierreJoueurs : QLabel** 
    # sceneMapJoueurs : QGraphicsScene** 

    # selectedTuile : QGraphicsItemGroup* 

    # onPlateauCameraMapMouseMoved(mousePos : QPointF)
    # onPlateauCameraMapMousePressed(mousePos : QPointF)
    # keyPressEvent(event : QKeyEvent*)

    + EcranJeu()
    
    + getAffichageJoueur() : AffichageGUI*
    + getAffichagesChantier() : AffichageGUI**
    + getAffichagesJoueursAdverses() : AffichageGUI**
    + getLabelTour() : QLabel*
    + getLabelRegles() : QLabel*

    + setUpWidgets(size_t playerCount)

    + setSelectedTuile(QGraphicsItemGroup* newSelectedTuile)
    + getSelectedTuilePosition() const : QPointF
    + removeSelectedTuile()

    + ready() {signal}
    + selectionTuileFinished(tuileSelected : int) {signal}
    + selectionPlacementFinished(placement : Vector2) {signal}
    + tourneSelectedTuile(sensHoraire : bool) {signal}
    + retour() {signal}
}

class AffichageGUI extends Affichage

MainWindow *- EcranType
EcranJeu -* MainWindow

JeuGUI *-- MainWindow

HexagoneGUIObject --o Hexagone
AffichageGUI -- HexagoneGUIObject
HexagoneGUIObject - EcranJeu

AffichageGUI -o EcranJeu
AffichageGUI -* JeuGUI

EcranJeu *-- CameraMap
EcranJeu *-- ChantierQGraphicsView


/'
Hexagone -- AffichageGUI
AffichageGUI *-- HexagoneGUIObject
JeuGUI *-- AffichageGUI

EcranType --* MainWindow
EcranJeu --* MainWindow
CameraMap --* EcranJeu
ChantierQGraphicsView --* EcranJeu
EcranJeu -- HexagoneGUIObject
MainWindow o-- AffichageGUI
JeuGUI *- MainWindow
'/

@enduml