@startuml score

abstract Serializable
abstract class Score extends Serializable {
    # scoreDécoré : Score*

    # scoreLocal(plateau : Plateau*) : int {pure virtual}
    + Score()
    + Score(Score *scoreDecore)
    + score(plateau : Plateau*) : int
}
note left : Est un décorateur

class ScoreCouleur extends Score {
    # scoreLocal(plateau : Plateau*) : int
    + ScoreCouleur()
    + ScoreCouleur(scoreDecore)
    + className() : string
}

class ScoreCouleurVariante extends Score {
    # scoreLocal(plateau : Plateau*) : int
    + ScoreCouleurVariante()
    + ScoreCouleurVariante(scoreDecore)
    + className() : string
}

class ScoreSoloArchitechteSpecifique extends Score {
    # scoreLocal(plateau : Plateau*) : int
    + className() : string
}

Player *-- "1" Score
Score *-- "1" Score

@enduml