on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and Deploy Doxygen Docs
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: '.'
            doxyfile-path: './Doxygen'
            enable-latex: true
